/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
export default {
    DocumentsSidebar: [
        'intro',
        {
            type: 'category',
            label: 'Reports',
            link: { type: 'doc', id: 'reports/index' },
            items: [{ type: 'autogenerated', dirName: 'reports' }],
        }
    ],
};
