[package]
name = "peras-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cbindgen = "0.26.0"

[lib]
name = "peras"
crate-type = [ "cdylib", "staticlib"]
