/**
 * FFI for Rust version of Peras node
 *
 *
 * Copyright 2024, Input Output HK Ltd
 * Licensed with: Apache-2.0
 */

#ifndef PERAS_LIBC
#define PERAS_LIBC

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque representation of a Peras node for foreign use
 */
typedef struct PerasNode PerasNode;

uintptr_t receive_message(struct PerasNode *node, uint8_t *buf, uintptr_t len);

void send_message(struct PerasNode *node, const uint8_t *buf, uintptr_t len);

/**
 * Creates and starts a new Peras node
 *
 */
struct PerasNode *start_node(const char *node_id, uint64_t node_stake);

void stop_node(struct PerasNode *node);

#endif /* PERAS_LIBC */
